### ISSUE TITLE
w_select_probs have NaN

### ISSUE THREAD

**Issue by yxy1314** [ColinLu50/NLP-Attack-LocalSearch#1]
在运行run_ga_imdb.py文件的时候，有一个bug：w_select_probs have NaN，导致perturb函数中的rand_idx = np.random.choice(x_len, 1, p=w_select_probs)[0]产生了报错：ValueError: probabilities contain NaN。虽然您针对这个bug在attack函数中加入了下面这段代码，但是还是在perturb函数中报错了，麻烦问一下这个情况您当初具体是怎么解决的？        
# BUG: w_select_probs have NaN  
        if np.sum(neigbhours_len) == 0:
            return None

**Comment by ColinLu50** [comment]
我在实验过程中使用现有的代码，没有遇到过该问题。

我认为可以用最直接的方法，把原来的`sum`判定改为关于NaN值的判定:

```
if np.isnan(w_select_probs).any():
   return None
```

出现NaN大概率是`neighbours_list`出了问题，建议您debug一下。
